openapi: 3.1.0
info:
  version: 1.0.0
  title: API for managing contacts
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: 'This is a documentation of Contacts App. Is a simple but functional web application that allows users to manage their personal contacts. It includes user authentication and CRUD (Create, Read, Update, Delete) operations for contacts.'
tags:
  - name: Contacts
    description: |
      - **Create Contact:** Add a new contact with details such as name, phone number, email, photo, and contact type. It is possible to mark contact favourite.
      - **Edit Contact:** Update contact details.
      - **Delete Contact:** Remove a contact permanently.
  - name: Auth
    description: |
      - **User-Specific Contacts:** Each user can see only their own contacts.
      - **Secure API:** Uses authentication tokens to protect user data.
servers:
  - url: http://localhost:3000
  - url: https://contacts-app-8l89.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{contactId}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{contactId}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{contactId}/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
